name: CI

on:
  push:
  pull_request:

jobs:
  fmt-and-clippy:
    name: Formatter and linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - run: cargo fmt --verbose --all -- --check
      - run: cargo clippy

  test:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --verbose
